# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ArtsLab
email: your-email@domain.com
description: >
  О дизайне и веб-разработке
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artslab.info" # the base hostname & protocol for your site
paginate:	7 # The number of posts to show per page on your homepage
comments: true
disqus_name: artslab

name: 'ArtsLab'
bio: >
  Блог для тех, кто интересуется разработкой сайтов,
  веб-дизайном и новыми событиями в интернете. В моем блоге Вы найдете
  записи на различные околокомпьютерные темы, обзоры сервисов и
  новинок, статьи по кодингу, советы, скрипты, темы и хаки
  для wordpress, уроки phostohop и многое другое.
author_image: "/assets/images/author.jpg"
twitter_username: artslab
github_username:  4gray
img_cdn: http://artslab.kissr.com/img

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: false

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
